// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Education = { institution: string, degree: string, from: string, to: string, detail: string | null, };

export type Entry = { title: string, subtitle: string | null, from: string, to: string, location: string | null, links: Array<Link>, bullets: Array<string>, };

export type Link = { label: string | null, href: string, icon: string, };

export type Meta = { siteTitle: string, tagline: string, footerCredit: string, visitorCountSeed: number, y2kCountdownTarget: string, };

export type Person = { name: string, role: string, location: string, summary: string, contact: Array<Link>, };

export type Profile = { meta: Meta, profile: Person, education: Array<Education>, experience: Array<Entry>, projects: Array<Entry>, achievements: Array<string>, positions: Array<string>, skills: Array<SkillGroup>, resume: ResumeLink, };

export type ResumeLink = { href: string, label: string, };

export type SkillGroup = { category: string, items: Array<string>, };
