// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Design = { title: string, kind: string | null, description: string, links: Array<Link>, };

export type Education = { institution: string, degree: string, from: string, to: string, detail: string | null, bullets: Array<string>, };

export type Entry = { title: string, 
/**
 * Optional category tag, e.g. "Systems" / "ML" / "Backend" / "Cloud" / "Embedded".
 */
type: string | null, 
/**
 * Free-form filter tags, e.g. "Open Source" / "ML" / "SDE" / "Intern".
 */
tags: Array<string>, subtitle: string | null, from: string, to: string, location: string | null, links: Array<Link>, bullets: Array<string>, };

export type Link = { label: string | null, href: string, icon: string, };

export type Meta = { siteTitle: string, tagline: string, footerCredit: string, visitorCountSeed: number, y2kCountdownTarget: string, };

export type Person = { name: string, role: string, location: string, summary: string, contact: Array<Link>, };

/**
 * A position of responsibility. Either a plain one-liner or an entry with
 * extra bullet points shown in a dropdown.
 */
export type Position = { title: string, bullets: Array<string>, } | string;

export type Profile = { meta: Meta, profile: Person, education: Array<Education>, experience: Array<Entry>, projects: Array<Entry>, achievements: Array<string>, positions: Array<Position>, testScores: Array<Position>, likes: Array<Position>, skills: Array<SkillGroup>, designs: Array<Design>, resume: Resume, };

export type Resume = { downloads: Array<ResumeVariant>, source: SourceLink | null, };

export type ResumeVariant = { 
/**
 * Short role key, e.g. "SDE" / "Embedded".
 */
role: string, label: string, href: string, };

export type SkillGroup = { category: string, 
/**
 * Role facets this group is relevant to, e.g. "ML" / "Systems" / "Backend" / "Cloud" / "SDE".
 */
roles: Array<string>, items: Array<string>, };

export type SourceLink = { label: string, href: string, };
